semi: false
useTabs: false
tabWidth: 2
endOfLine: lf
printWidth: 80
singleQuote: true
arrowParens: avoid
proseWrap: preserve
insertPragma: false
requirePragma: false
trailingComma: none
bracketSpacing: true
jsxSingleQuote: true
quoteProps: as-needed
htmlWhitespaceSensitivity: css
embeddedLanguageFormatting: auto
